Fixed SAL handing.
AdaCore/cuda pull request #77
Opened 2022-10-19 20:58 UTC by QuentinOchem

This patches changes the way the compilation and library build sequence. Compilation now stops at the production of the assembly file, linking a static library results in a cubin, linking a dynamic library will result in a fatbinary, to be included in a host main.

TN: VA19-044

2022-10-24 15:31 UTC, glacambre requested changes
I don't have a good understandingg of all this, but I don't see any glaring issues.

The code should probably be reformatted before being merged though.

2022-10-24 16:37 UTC, QuentinOchem commented on wrapper/src/gnatcuda_wrapper.adb
> +         end GNATCUDA_Wrapper;
Indeed - re-doing a file format.

2022-10-24 16:40 UTC, QuentinOchem commented on wrapper/src/gnatcuda_wrapper.adb
> +                 and then Argument (J - 1) /= "-o"))
-l and -L are actually not flags. ie you write -lsomething instead of -l something.

2022-10-24 16:40 UTC, QuentinOchem commented on wrapper/src/gnatcuda_wrapper.adb
> +         end GNATCUDA_Wrapper;
Yeah - fixing... :P

2022-10-24 16:43 UTC, QuentinOchem commented on wrapper/src/gnatcuda_wrapper.adb
> +         LD := To_Unbounded_String ("ld");
Not sure if that makes a fundamental difference to compute the value from HT_Str or HT - in all cases you need an if statement to either set a value or return one.

2022-10-24 18:07 UTC, ohenley approved these changes
+1

2022-10-25 08:08 UTC, glacambre commented on wrapper/src/gnatcuda_wrapper.adb
> +                 and then Argument (J - 1) /= "-o"))
They are flags:
```
>ld tmp.o -l SDL2
>echo $?
0
```

2022-10-25 08:10 UTC, glacambre approved these changes

2022-10-25 13:03 UTC, merged